### ISSUE TITLE
.gitpod.ymlの編集

### ISSUE THREAD

**Issue by AkiUnleash** [AkiUnleash/hands-on-nextjs-supabase#27]
現状だと、２度目に開いたときもcommandが動いてしまい、.env.localに追加で記載されてしまう。

```yml
tasks:
  - init: yarn install
    command: touch .env.local && echo NEXT_PUBLIC_SUPABASE_URL= >> .env.local && echo NEXT_PUBLIC_SUPABASE_KEY= >> .env.local
```
